inherit_from:
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop.yml

  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-minitest.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-performance.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-rails.yml

  - .rubocop_todo.yml

Rails:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Metrics/BlockLength:
  Exclude:
    - config/initializers/devise.rb
    - config/routes/**/*
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/environments/*.rb
    - config/routes.rb
    - node_modules/**/*
    - vendor/bundle/**/*
