version: "3.4"

services:
  web:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
        - RAILS_ENV=$RAILS_ENV
    environment:
      DB_HOST: db
    ports:
      - "80:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle
      - ./.bundle:/app/.bundle
      - ./node_modules:/app/node_modules
  db:
    image: "postgres:13.2"
    environment:
      POSTGRES_USER: vites
      POSTGRES_PASSWORD: vites
  test:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
        - RAILS_ENV=$RAILS_ENV
        - NODE_ENV=$NODE_ENV
    environment:
      DB_HOST: db
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
      RAILS_ENV: $RAILS_ENV
      NODE_ENV: $NODE_ENV
    depends_on:
      - db
    volumes:
      - $HOME/bundle:/app/vendor/bundle
      - $HOME/.bundle_config:/app/.bundle
      - $HOME/node_modules:/app/node_modules
      - $HOME/coverage:/app/coverage
