# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(File.expand_path('.ruby-version', __dir__))

gem 'bootsnap', '>= 1.4.4', require: false
gem 'puma', '~> 5.3'
gem 'rails', '~> 6.1.3', '>= 6.1.3.1'

gem 'pg', '~> 1.1'
gem 'pghero', '>= 2.7.0'
gem 'pg_search', '>= 2.3.2'
gem 'rein', '>= 5.1.0'

gem 'devise', github: 'heartcombo/devise'
gem 'omniauth-oauth2', '>= 1.7.1'
gem 'omniauth-rails_csrf_protection', '>= 1.0.0'

gem 'pundit', '>= 2.1.0'

gem 'cocoon'
gem 'simple_form', '>= 5.1.0'

gem 'jbuilder', '~> 2.10'

gem 'sassc', '~> 2.4.0'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.3'

gem 'telephone_number'
gem 'valid_email2'

gem 'pagy', '~> 4.6'
gem 'rollbar'

gem 'lograge'

group :development, :test do
  gem 'brakeman', require: false
  gem 'bullet', github: 'flyerhzm/bullet'
  gem 'bundler-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'erb_lint', require: false
  gem 'lol_dba', '>= 2.2.0'
  gem 'rubocop'
  gem 'rubocop-minitest'
  gem 'rubocop-performance'
  gem 'rubocop-rails', '>= 2.5.2'
  gem 'simplecov', require: false
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 4.1.0'
  # gem 'rack-mini-profiler', '~> 2.0'
end

group :test do
  gem 'capybara'
  gem 'minitest-focus'
  gem 'simplecov-cobertura'
  gem 'webdrivers'
end
